# Generated by Django 4.2.7 on 2024-01-02 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_main', '0002_board_image_board_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
