# Generated by Django 4.2.7 on 2024-01-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_main', '0003_alter_board_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.FileField(default='', upload_to='svg/'),
        ),
    ]
