# Generated by Django 4.2.7 on 2024-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_main', '0004_alter_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tag2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
