# Generated by Django 4.2.7 on 2024-01-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_main', '0005_board_tag2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
